### ISSUE TITLE
A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by jfeldstein** [chillu/github-dashing#31]
Spotting this in my console logs. 

    ================================================================================
    scheduler caught exception:
    A JSON text must at least contain two octets!
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/json-1.7.7/lib/json/common.rb:155:in `initialize'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/json-1.7.7/lib/json/common.rb:155:in `new'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/json-1.7.7/lib/json/common.rb:155:in `parse'
    /Users/jordan/Code/kiddom/github-dashing-master/jobs/travis.rb:20:in `block in <top (required)>'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
    /Users/jordan/.rvm/gems/ruby-2.1.5@kiddom-dashing/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
    ================================================================================

**Comment by fkrauthan** [comment]
Same for me. But I guess this is not longer under active development?

**Comment by fkrauthan** [comment]
Wait I fixed it in your .env replace `TRAVIS_BRANCH_BLACKLIST=` with `TRAVIS_BRANCH_BLACKLIST={}`
