### ISSUE TITLE
Error running 'dashing start': 'failed to load command: thin'

### ISSUE THREAD

**Issue by vmassol** [chillu/github-dashing#36]
Hi,

Trying to use this nice-looking project but I'm failing to run `dashing start`:

```
vmassol ~/dev/github-dashing (master) $ dashing start
bundler: failed to load command: thin (/usr/local/bin/thin)
LoadError: Could not open library 'c': dlopen(c, 5): image not found.
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
  /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib'
  /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
  /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.1/lib/ethon/libc.rb:8:in `<module:Libc>'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.1/lib/ethon/libc.rb:6:in `<module:Ethon>'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.1/lib/ethon/libc.rb:1:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.1/lib/ethon.rb:14:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
  /Library/Ruby/Gems/2.0.0/gems/typhoeus-1.0.1/lib/typhoeus.rb:2:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
  config.ru:11:in `block in <main>'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'
vmassol ~/dev/github-dashing (master) $ 
```

I've executed `bundle install`and I've even executed `sudo gem install thin`.

Any idea? (I'm on Mac and a newbie when it comes to ruby).

Thanks

**Comment by vmassol** [comment]
Seems related to OSX El Capitan: https://github.com/ffi/ffi/issues/461
